fragment ChapterTypeFragment on ChapterType {
	isBookmarked
	isDownloaded
	isRead
	id
	chapterNumber
	fetchedAt
	lastPageRead
	name
	sourceOrder
	uploadDate
	pageCount
	scanlator
}

fragment MangaTypeFragment on MangaType {
	artist
	author
	description
	genre
	id
	inLibrary
	lastFetchedAt
	realUrl
	status
	title
	thumbnailUrl
	unreadCount
	downloadCount
	lastReadChapter {
		lastReadAt
	}
	meta {
		value
		key
	}
	source {
		displayName
	}
	categories {
		nodes {
			id
		}
	}
}

fragment SourceTypeFragment on SourceType {
	id
	displayName
	iconUrl
	lang
}

fragment ExtensionTypeFragment on ExtensionType {
	name
	versionName
	pkgName
	lang
	iconUrl
	isNsfw
	isInstalled
	isObsolete
	hasUpdate
}

fragment CategoryTypeFragment on CategoryType {
	id
	default
	order
	name
	mangas {
		totalCount
	}
}
