fragment ChapterTypeFragment on ChapterType {
	isBookmarked
	isDownloaded
	isRead
	id
	chapterNumber
	fetchedAt
	lastPageRead
	name
	sourceOrder
	uploadDate
	pageCount
	scanlator
}

fragment MangaTypeFragment on MangaType {
	artist
	author
	description
	genre
	id
	inLibrary
	lastFetchedAt
	realUrl
	status
	title
	thumbnailUrl
	unreadCount
	downloadCount
	lastReadChapter {
		lastReadAt
	}
	meta {
		value
		key
	}
	source {
		displayName
	}
	categories {
		nodes {
			id
		}
	}
}

fragment SourceTypeFragment on SourceType {
	id
	displayName
	iconUrl
	lang
}

fragment PreferenceFragment on Preference {
	... on CheckBoxPreference {
		CheckBoxCheckBoxCurrentValue: currentValue
		summary
		CheckBoxDefault: default
		key
		CheckBoxTitle: title
	}
	... on EditTextPreference {
		EditTextCurrentValue: currentValue
		EditTextDefault: default
		EditTextTitle: title
		text
		summary
		key
		dialogTitle
		dialogMessage
	}
	... on SwitchPreference {
		SwitchCurrentValue: currentValue
		summary
		key
		SwitchDefault: default
		SwitchTitle: title
	}
	... on MultiSelectListPreference {
		dialogMessage
		dialogTitle
		MultiSelectListTitle: title
		summary
		key
		entryValues
		entries
		MultiSelectListDefault: default
		MultiSelectListCurrentValue: currentValue
	}
	... on ListPreference {
		ListCurrentValue: currentValue
		ListDefault: default
		ListTitle: title
		summary
		key
		entryValues
		entries
	}
}

fragment FilterFragment on Filter {
	... on TriStateFilter {
		__typename
		name
		TriStateDefault: default
	}
	... on CheckBoxFilter {
		__typename
		CheckBoxDefault: default
		name
	}
	... on TextFilter {
		__typename
		name
		TextDefault: default
	}
	... on SortFilter {
		__typename
		values
		name
		SortDefault: default {
			ascending
			index
		}
	}
	... on SeparatorFilter {
		__typename
		name
	}
	... on SelectFilter {
		__typename
		values
		name
		SelectDefault: default
	}
	... on HeaderFilter {
		__typename
		name
	}
}

fragment ExtensionTypeFragment on ExtensionType {
	name
	versionName
	pkgName
	lang
	iconUrl
	isNsfw
	isInstalled
	isObsolete
	hasUpdate
}
