# // Copyright (c) 2023 Contributors to the Suwayomi project
# //
# // This Source Code Form is subject to the terms of the Mozilla Public
# // License, v. 2.0. If a copy of the MPL was not distributed with this
# // file, You can obtain one at http://mozilla.org/MPL/2.0/.

# // This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# // For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

subscription downloadChanged {
	downloadChanged {
		queue {
			chapter {
				name
				id
			}
			manga {
				title
				thumbnailUrl
				id
			}
			progress
			state
			tries
		}
		state
	}
}

subscription downloadsOnChapters {
	downloadChanged {
		queue {
			progress
			state
			chapter {
				id
			}
			manga {
				id
			}
		}
		state
	}
}
