version: '3.7'
services:
  vui3:
    image: ghcr.io/suwayomi/tachidesk-vui
    ports:
      - '9013:8080'
    environment:
      - tachidesk=http://tachidesk:4567/
      # will proxy the tachidesk server to the UI
      # if you plan on proxying it externally then this is unnecessary
    restart: unless-stopped

  vui3-dev:
    build:
      context: .
      target: 'develop-stage'
    ports:
      - '5173:5173'
    environment:
      - VITE_URL=http://tachidesk:4567
    volumes:
      - '.:/app'
    command: /bin/sh -c "npm i && npm run dev -- --host"
    restart: unless-stopped
