version: '3.7'
services:
  vui3:
    image: ghcr.io/suwayomi/suwayomi-vui
    ports:
      - '9013:8080'
    environment:
      - suwayomi=http://suwayomi:4567
      # will proxy the suwayomi server to the UI
      # if you plan on proxying it externally then this is unnecessary
      - theme=skeleton
      # defaults to skeleton
      # is for the SSR to stop off first loads 
      # any of the themes avalabe in VUI
      # skeleton, wintry, crimson, gold-nouveau, hamlindigo, modern, rocket, sahara, seafoam, vintage
    restart: unless-stopped

  vui3-dev:
    build:
      context: .
      target: 'develop-stage'
    ports:
      - '5173:5173'
    environment:
      - VITE_URL=http://suwayomi:4567
    volumes:
      - '.:/app'
    command: /bin/sh -c "bun i && bun run dev --host"
    restart: unless-stopped
