name: Lint

on:
  push:
    branches: ["main", "Release"]
  pull_request:
    branches: ["main", "Release"]
jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Use bun 1.0.10
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install bun dependencies
        run: bun i
      - name: Run linters
        run: |
          bun run lint
