# Copyright (c) 2022 Contributors to the Suwayomi project
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Copyright (c) 2022 Contributors to the Suwayomi project
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: BuildElectron

on:
  pull_request:
    branches: ["Release"]

jobs:
  buildLinux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: "npm"
      - name: Generate Tag Name
        id: GenTagName
        run: |
          genTag="r$(git rev-list HEAD --count)"
          echo "$genTag"
          echo "value=$genTag" >> $GITHUB_OUTPUT
      - run: npm ci
      - run: npm run buildElectron
      - name: Upload CI Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./dist/electron/Tachidesk-VUI.AppImage,./dist/electron/Tachidesk-VUI.zip"
          tag: ${{ steps.GenTagName.outputs.value }}
