# Copyright (c) 2022 Contributors to the Suwayomi project
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Lint

on:
  pull_request:
    branches: ['main', 'Release']
    paths-ignore:
      - '**/README.md'
      - '.github/workflows/**.yml'
      - '**/default.conf'

jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use bun latest
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install bun dependencies
        run: bun i
      - name: Run linters
        run: bun run lint
